type Query {
    loginUser(username: String, password: String): Boolean
    loggedIn: Boolean
}

type Mutation {
    signUpUser(firstname: String, lastname: String, username: String, password: String, email: String): Boolean
    createProject(name: String, env: String): Boolean
}