DROP DATABASE IF EXISTS saturn;

CREATE DATABASE IF NOT EXISTS saturn;

USE saturn;

CREATE TABLE users(
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `fname` VARCHAR(255) NOT NULL,
    `lname` VARCHAR(255) NOT NULL,
    `uname` VARCHAR(255) NOT NULL,
    `pword` VARCHAR(255) NOT NULL,
    `salt`  VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- Creation Time
    `utime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP   -- Last Update Time
);

CREATE TABLE projects(
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `env` ENUM('python', 'c'),
    `owner` VARCHAR(255) NOT NULL,
    `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- Creation Time
    `utime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP   -- Last Update Time
);

